import { useMemo, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, AtSign, MapPin, Menu, Phone, X } from 'lucide-react'
import { dishes, images, dailyMenu, menuCategories, MenuCategory, restaurant } from './data/restaurant'
import { ReservationForm } from './components/ReservationForm'
import { singlePageNav } from './lib/routes'

export default function App() {
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const [category, setCategory] = useState<MenuCategory>('Todo')
  const filteredDishes = useMemo(() => category === 'Todo' ? dishes : dishes.filter((dish) => dish.category === category), [category])
  const closeMenu = () => setIsMenuOpen(false)
  return <>
    <header className="header"><a className="brand" href="#inicio" onClick={closeMenu}><i />EL COMAL</a><nav className={isMenuOpen ? 'nav nav-open' : 'nav'}>{singlePageNav.map((item) => <a key={item.target} href={`#${item.target}`} onClick={closeMenu}>{item.label}</a>)}</nav><a className="button header-book" href="#reservas">Reservar mesa</a><button className="menu-button" aria-label={isMenuOpen ? 'Cerrar menú' : 'Abrir menú'} onClick={() => setIsMenuOpen((open) => !open)}>{isMenuOpen ? <X /> : <Menu />}</button></header>
    <main>
      <section id="inicio" className="hero"><img src={images.heroImage} alt="Plato de mole en la sala de El Comal" /><div className="hero-shade" /><div className="hero-content"><p className="eyebrow hero-eyebrow">Calella de Mar</p><h1>El Comal</h1><p className="hero-subtitle">Cocina mexicana con fuego,<br />tiempo y memoria.</p><a className="hero-link" href="#reservas">Reserva una mesa <ArrowDownRight size={18} /></a></div><a className="scroll-cue" href="#mesa"><span />Descubre</a></section>
      <section id="mesa" className="story section"><div className="story-copy"><p className="eyebrow">Nuestra mesa</p><h2>La cocina empieza<br />con un gesto.</h2><p>El comal es el centro de nuestras noches. Una cocina hecha al momento, con maíz, brasas y recetas que llegan de lejos para quedarse cerca del mar.</p><a className="text-link" href="#carta">Conoce nuestra carta <ArrowDownRight size={18} /></a></div><div className="story-image"><img src={images.chefImage} alt="Tortilla preparada a mano sobre el comal" /></div></section>
      <section id="carta" className="menu-section section"><div className="section-heading"><p className="eyebrow">La carta</p><h2>Sabores que<br />piden volver.</h2><p>Una mesa para compartir despacio.</p></div><div className="menu-layout"><div className="category-list" role="tablist" aria-label="Categorías de carta">{menuCategories.map((item) => <button key={item} className={category === item ? 'category-active' : ''} onClick={() => setCategory(item)} role="tab" aria-selected={category === item}>{item}</button>)}</div><div className="dish-list" aria-live="polite">{filteredDishes.map((dish) => <article className="dish" key={dish.name}><div><h3>{dish.name} {dish.tag && <em>{dish.tag}</em>}</h3><p>{dish.description}</p></div><span>{dish.price}</span></article>)}</div><div className="menu-image"><img src={images.tacosImage} alt="Tacos de maíz con piña a la brasa" /></div></div></section>
      <section id="menu" className="daily-menu"><div><p className="eyebrow">Menú de mediodía</p><h2>Entre semana,<br />a la mexicana.</h2><p>De martes a viernes · 13:00 a 15:30</p></div><div className="daily-courses">{dailyMenu.map(([course, dish]) => <div key={course}><span>{course}</span><p>{dish}</p></div>)}<strong>24 € <small>por persona</small></strong></div></section>
      <section id="reservas" className="reservation section"><div className="reservation-copy"><p className="eyebrow">Reserva tu mesa</p><h2>Hay noches<br />que empiezan aquí.</h2><p>Déjanos tus datos y te confirmaremos la mesa en cuanto podamos. Para grupos de más de 12 personas, escríbenos directamente.</p><a href={`tel:${restaurant.phoneHref}`} className="phone-link"><Phone size={18} /> {restaurant.phone}</a></div><ReservationForm /></section>
      <section id="contacto" className="contact"><div className="contact-top"><div><p className="eyebrow">Encuéntranos</p><h2>Calella de Mar,<br />con México en la mesa.</h2></div><a className="button button-outline" href={restaurant.mapUrl} target="_blank" rel="noreferrer">Cómo llegar <ArrowUpRight size={17} /></a></div><div className="contact-grid"><div className="address"><MapPin size={20} /><p>{restaurant.address}</p></div><div className="opening"><p className="eyebrow">Horario</p>{restaurant.hours.map((hour) => <p key={hour}>{hour}</p>)}</div><div className="contact-links"><a href={`mailto:${restaurant.email}`}>{restaurant.email}</a><a href={restaurant.instagram} target="_blank" rel="noreferrer"><AtSign size={18} /> @elcomal.restaurant</a></div><a className="map-panel" href={restaurant.mapUrl} target="_blank" rel="noreferrer"><span className="map-pin"><MapPin fill="currentColor" /></span><span>EL COMAL</span><i /><i /><i /></a></div></section>
    </main>
    <footer className="footer"><a className="brand" href="#inicio"><i />EL COMAL</a><p>Fuego, maíz y una mesa que siempre espera.</p><p>© 2026 El Comal · Calella de Mar</p></footer>
  </>
}
